name: Build EuroScope Plugin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      
    - name: Setup vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
        
    - name: Install dependencies (manifest mode)
      run: |
        .\vcpkg\vcpkg install --triplet=x86-windows
        
    - name: Handle EuroScope Library
      run: |
        if (!(Test-Path "EuroScopePlugInDll.lib")) {
          Write-Host "EuroScopePlugInDll.lib not found - continuing without it"
          Write-Host "Plugin will compile but may need manual linking"
        } else {
          Write-Host "EuroScopePlugInDll.lib found"
        }
        
    - name: Configure CMake
      run: |
        cmake -B build -S . "-DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake" -A Win32
        
    - name: Build
      run: |
        cmake --build build --config Release
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: EuroScope-Plugin
        path: build/Release/*.dll
        if-no-files-found: warn
        
    - name: Upload build logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: build/**/*.log
        if-no-files-found: ignore
